name: 01 - First WorkFlow.
#on: [push, workflow_dispatch]
on: workflow_dispatch

jobs: 
    job1:
        name: echo-hello
        runs-on: ubuntu-latest
        steps:
            - name: Saludar
              run: echo "¡Hola, mundo!"

    job2:
        name: echo-goodbye
        runs-on: ubuntu-latest
        steps:
            - name: Paso correcto
              run: |
                echo "Correcto"
                exit 0
            - name: Decir adiós
              run: echo "¡Adiós!"