name: 03 - Runners de workflow
on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps: 
      - name: Mostrar SO
        run: |
            cd my-app
            npm run test