name: 16 - Working with Matrices
on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{matrix.node }}
        strategy:
            matrix:
                node: [18.x, 20.x y 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node }}