name: 16 - 2 - Working with Matrices 2
on:
    workflow_dispatch:

jobs:
    include-example:
        runs-on: ubuntu-latest
        name: ${{ matrix.color }}-${{matrix.shape }}-${{matrix.size }}
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include:
                  - color: red
                    opacity: 75
                  - shape: circle
                    opacity: 100
                  - color: red
                    shape: triangle
                  - opacity: 50
        steps:
            - name: Dummy step
              run: | 
                echo "color: ${{matrix.color}} - shape: ${{matrix.shape}} - size: ${{matrix.size}} - opacity: ${{matrix.opacity}}"
                