name: 17 - Working with Environments 2
on:
    workflow_dispatch: 

jobs:
    deploy-pre:
        runs-on: ubuntu-latest
        env:
            MY_ENV_VALUE: pre
        steps:
            - name: Echo vars
              run: | 
                echo "Deploying to ${{env.MY_ENV_VALUE}}"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-pre
        steps:
            - name: E2E tests
              run: echo "Running E2E"
    deploy-pro:
        runs-on: ubuntu-latest
        needs: e2e-tests
        env:
            MY_ENV_VALUE: pro
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo vars
              run: echo "Deploying to ${{env.my-env-value}}"