name: 18 - 3 - Reusable Workflows
on:
    workflow_dispatch: 

jobs:
    deploy:
        uses: ./.github/workflows/18-1-reusable-workflow.yaml
        with:
            target-directory: a
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy
        #uses: //.github/workflows/e2e.yaml@main
        steps:
            - name: Desencadenar otro workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                workflow: 'e2e.yml'
                token: ${{ secrets.GH_TOKEN }}
                repo: Mansoldev/gha-course-example-e2e
                ref: 'main'